//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class bitacora
    {
        public int id_bitacora { get; set; }
        public int id_dispositivo { get; set; }
        public System.DateTime fechaEvento { get; set; }
        public string descripcionEvento { get; set; }
    
        public virtual dispositivo dispositivo { get; set; }
    }
}
