//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class domoticaEntities : DbContext
    {
        public domoticaEntities()
            : base("name=domoticaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bitacora> bitacora { get; set; }
        public virtual DbSet<dispositivo> dispositivo { get; set; }
        public virtual DbSet<tipoDispositivo> tipoDispositivo { get; set; }
        public virtual DbSet<zona> zona { get; set; }
        public virtual DbSet<zonaDispositivo> zonaDispositivo { get; set; }
    }
}
